services:
  nats:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222 
      - 8222:8222

  nginx:
    image: warpy_nginx
    volumes:
    - ./dev_env/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:9999

  redis:
    image: redis:6.2.4-alpine
    ports:
      - 6379:6379

  backend:
    image: node:16.0.0-alpine
    env_file:
      dev_env/backend.env
    volumes:
      - ./:/warpy
    working_dir: /warpy/backend
    command: yarn start:dev

  postgres:
    image: postgres:13-alpine
    ports:
    - 5432:5432
    volumes:
      - /data/warpy-pg/:/var/lib/postgresql
    environment:
      POSTGRES_USER: warpy
      POSTGRES_PASSWORD: warpy222
      POSTGRES_DB: warpy

  ranker:
    image: node:16.0.0-alpine
    env_file:
      dev_env/ranker.env
    volumes:
      - ./:/warpy
    working_dir: /warpy/ranker
    command: yarn start:dev

  ws_gateway:
    image: node:16.0.0-alpine
    env_file:
      dev_env/ws_gateway.env
    volumes:
      - ./:/warpy
    working_dir: /warpy/ws_gateway
    command: yarn start:dev

  media:
    image: node:16.0.0-alpine
    env_file:
      dev_env/media.env
    volumes:
      - ./:/warpy
    working_dir: /warpy/media
    command: yarn start:dev
