/// Flutter icons WarpyIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WarpyIcons
///      fonts:
///       - asset: fonts/WarpyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WarpyIcons {
  WarpyIcons._();

  static const _kFontFam = 'WarpyIcons';
  static const String? _kFontPkg = null;

  static const IconData hand = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData claps = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData black_hole = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
